name: "AI Code Reviewer"
description: "Analyze PR code changes and send to AI Review API"
author: "TuanPA"
inputs:
  api_key:
    description: "Project API Token provided by LiftSoft"
    required: true
  api_url:
    description: "Full URL of the Review API"
    required: false
  github_token:
    description: "Standard GitHub Token for comments"
    required: true
  language:
    description: "Output language (en or vi)"
    default: "vi"
    required: false
  custom_instructions:
    description: "Custom instructions for the AI reviewer (e.g. 'Focus on security')"
    required: false

runs:
  using: "composite"
  steps:
    # 1. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 2. Install Python dependencies
    - name: Install dependencies
      shell: bash
      run: pip install requests

    # 3. Run Python Script
    - name: Generate Review Payload
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}
        BRANCH_NAME: ${{ github.head_ref }}
        PR_URL: ${{ github.event.pull_request.html_url }}
        CREATOR: ${{ github.event.pull_request.user.login }}
        BASE_REF: ${{ github.base_ref }}
        HEAD_REF: ${{ github.sha }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        REVIEWERS_JSON: ${{ toJson(github.event.pull_request.requested_reviewers) }}
        OUTPUT_LANG: ${{ inputs.language }}
        CUSTOM_INSTRUCTIONS: ${{ inputs.custom_instructions }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PAYLOAD_OUTPUT_PATH: payload.json
      # Ensure generate_payload.py exists in your action's scripts/ folder
      run: python ${{ github.action_path }}/scripts/generate_payload.py

    # 4. Call API
    - name: Send Info to API
      shell: bash
      run: |
        API_URL="${{ inputs.api_url }}"
        if [ -z "$API_URL" ]; then
          API_URL="https://api.freedl.blog/api/v1/review-code/"
        fi

        echo "Sending payload to LiftSoft API..."
        # Capture HTTP code and content separately for better error handling
        HTTP_CODE=$(curl -s -o api_response.json -w "%{http_code}" -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -H "X-API-Key: ${{ inputs.api_key }}" \
          -d @payload.json)

        echo "API Response Status Code: $HTTP_CODE"

        if [ "$HTTP_CODE" -ne 200 ]; then
          echo "Error: API returned status $HTTP_CODE"
          cat api_response.json
          exit 1
        fi

    # 5. Comment on PR (Safe Python Extraction)
    - name: Extract Review and Save
      shell: bash
      run: |
        python3 -c "
        import json
        import sys

        try:
            with open('api_response.json', 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            review = data.get('review_text', '')
            # Check for None explicitly or empty string
            if not review or review == 'None' or not review.strip():
                print('Review generation failed or empty.')
                sys.exit(1)
            
            # Write directly to file to avoid shell expansion issues
            with open('review_comment.md', 'w', encoding='utf-8') as f:
                f.write(review)
        except Exception as e:
            print(f'Error extracting review: {e}')
            sys.exit(1)
        "

    - name: Comment on Pull Request
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: review_comment.md
        pr_number: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      continue-on-error: true

    # 6. Create Issue if needed (Safe Python Extraction)
    - name: Create GitHub Issue
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: |
        # Use Python to check and prepare issue body safely
        python3 -c "
        import json
        import os
        import sys

        try:
            with open('api_response.json', 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            issues = data.get('issues_text', '')
            
            # Only create issue file if there are actual issues
            if issues and issues != 'None' and issues.strip():
                pr_url = os.environ.get('PR_URL', '')
                with open('issue_body.md', 'w', encoding='utf-8') as f:
                    f.write(f'Review caused by PR: {pr_url}\n\n')
                    f.write(issues)
                print('ISSUES_FOUND')
            else:
                print('NO_ISSUES')
        except Exception as e:
            print(f'Error extracting issues: {e}')
            sys.exit(1)
        " > issue_check_status.txt
        
        STATUS=$(cat issue_check_status.txt)
        
        if [ "$STATUS" == "ISSUES_FOUND" ]; then
          echo "Creating GitHub Issue..."
          gh issue create --title "🚨 Code Review Issues: $PR_TITLE" --body-file issue_body.md --repo ${{ github.repository }} || true
        else
          echo "No issues to report."
        fi
        